# Generated by Django 4.1.6 on 2023-02-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_job', models.CharField(max_length=255, verbose_name='Обязанность')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=9, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('wats_up_number', models.CharField(blank=True, max_length=9, verbose_name='Ватсап')),
                ('telegram_number', models.CharField(blank=True, max_length=9, verbose_name='Телеграм')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Умение')),
                ('skill_value', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень скила')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('years', models.CharField(max_length=10, verbose_name='Года работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('job_skill', models.ManyToManyField(related_name='job_skill', to='resume.jobskills')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scool_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специальность')),
                ('years', models.CharField(max_length=10, verbose_name='Года учебы')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.user', verbose_name='Пользователь')),
            ],
        ),
    ]
