# Generated by Django 4.1.6 on 2023-02-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wats_up_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Ватсап'),
        ),
    ]
