# Generated by Django 4.1.6 on 2023-02-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_user_phone_alter_user_telegram_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='scool_name',
            new_name='school_name',
        ),
    ]
