# Generated by Django 4.1.6 on 2023-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_scool_name_education_school_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образования'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='jobskills',
            options={'verbose_name': 'Обязанность на работе', 'verbose_name_plural': 'Обязанности на работе'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Умения', 'verbose_name_plural': 'Умения'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.CharField(max_length=15, verbose_name='Года работы'),
        ),
    ]
