# Generated by Django 4.1.6 on 2023-02-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_language', models.CharField(max_length=255, verbose_name='Язык')),
                ('level', models.CharField(max_length=255, verbose_name='Уровень владения')),
            ],
            options={
                'verbose_name': 'Языки',
                'verbose_name_plural': 'Языки',
            },
        ),
    ]
