# Generated by Django 4.1.6 on 2023-02-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_education_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.CharField(max_length=50, verbose_name='Года работы'),
        ),
    ]
