# Generated by Django 4.1.6 on 2023-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='tooltip',
            field=models.TextField(default='', verbose_name='ToolTip'),
        ),
    ]
