# Generated by Django 4.1.6 on 2023-02-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_skills_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(default='Expert', max_length=100, verbose_name='Уровень владения'),
        ),
    ]
